# Generated by Django 4.2.8 on 2026-09-06 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_candidate_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='interview_remarks',
            field=models.TextField(blank=True, help_text='Interview remarks or candidate assessment notes'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='knowledge_score',
            field=models.PositiveIntegerField(blank=True, help_text='Candidate knowledge score out of 100%', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
