# Generated by Django 4.2.8 on 2026-09-06 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_candidate_interview_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='experience_score',
            field=models.PositiveIntegerField(blank=True, help_text='Candidate experience score out of 100%', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='candidate',
            name='qualification_score',
            field=models.PositiveIntegerField(blank=True, help_text='Candidate qualification score out of 100%', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
