# Generated by Django 4.2.8 on 2026-09-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_remove_stale_named_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('ANNUAL', 'Annual'), ('SICK', 'Sick'), ('CASUAL', 'Casual'), ('UNPAID', 'Unpaid'), ('MATERNITY', 'Maternity'), ('PATERNITY', 'Paternity'), ('COMPASSIONATE', 'Compassionate'), ('STUDY', 'Study'), ('BEREAVEMENT', 'Bereavement')], max_length=20),
        ),
    ]
