# Generated by Django 4.2.8 on 2026-08-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_add_salary_ratios_and_compliance_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollentry',
            name='employer_borne_deductions',
            field=models.BooleanField(default=False, help_text='If True, employer absorbs statutory deductions — employee takes home the full gross'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employer_borne_deductions',
            field=models.BooleanField(default=False, help_text='If True, employer absorbs statutory deductions — employee takes home the full gross'),
        ),
    ]
